"""add plural to specification

Revision ID: aa879f1fc7fe
Revises: 027a45885b21
Create Date: 2023-05-31 12:58:10.627401

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa879f1fc7fe"
down_revision = "027a45885b21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification", schema=None) as batch_op:
        batch_op.add_column(sa.Column("plural", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification", schema=None) as batch_op:
        batch_op.drop_column("plural")

    # ### end Alembic commands ###
