"""add diagram to specification

Revision ID: b38467aa03b0
Revises: aa879f1fc7fe
Create Date: 2023-06-01 10:39:12.060871

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b38467aa03b0"
down_revision = "aa879f1fc7fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification", schema=None) as batch_op:
        batch_op.add_column(sa.Column("diagram", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification", schema=None) as batch_op:
        batch_op.drop_column("diagram")

    # ### end Alembic commands ###
